import { readdir, readFile, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const srcDir = new URL("src/", root);
const languagesDir = new URL("languages/", srcDir);

const IMPORT_RE =
	/^import\s*\{([\s\S]*?)\}\s*from\s*['"]\.\/([\w.-]+)['"];?\s*$/gm;
const EXPORT_RE = /^export (function|async function|const|let)/gm;

async function buildLanguageRegistry() {
	const manifest = JSON.parse(
		await readFile(new URL("index.json", languagesDir), "utf8"),
	);
	const entries = await Promise.all(
		manifest.map(async (file) => {
			const language = JSON.parse(
				await readFile(new URL(file, languagesDir), "utf8"),
			);
			return [language.code, language];
		}),
	);
	return Object.fromEntries(entries);
}

async function bundleModules() {
	const files = (await readdir(srcDir)).filter((file) => file.endsWith(".js"));
	const sources = new Map();
	for (const file of files)
		sources.set(file, await readFile(new URL(file, srcDir), "utf8"));

	const importedFilesOf = (source) =>
		[...source.matchAll(IMPORT_RE)].map((match) => match[2]);

	const order = [];
	const visiting = new Set();
	const visited = new Set();
	function visit(file) {
		if (visited.has(file)) return;
		if (visiting.has(file))
			throw new Error(`Circular import detected involving ${file}`);
		if (!sources.has(file)) throw new Error(`Unknown module import: ./${file}`);
		visiting.add(file);
		for (const dependency of importedFilesOf(sources.get(file)))
			visit(dependency);
		visiting.delete(file);
		visited.add(file);
		order.push(file);
	}
	for (const file of files) visit(file);

	return order
		.map((file) => {
			const body = sources
				.get(file)
				.replace(IMPORT_RE, "")
				.replace(EXPORT_RE, "$1")
				.trim();
			return `// ---- src/${file} ----\n${body}\n`;
		})
		.join("\n");
}

const languageRegistry = await buildLanguageRegistry();
const modules = await bundleModules();

const banner =
	"// Generated by `npm run build` from src/ — do not edit directly.\n\n";
const registry = `// ---- src/languages/*.json ----\nconst languageRegistry = ${JSON.stringify(languageRegistry)};\n\n`;
await writeFile(new URL("app.js", root), banner + registry + modules);
