import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const srcDir = new URL("src/", root);
const languagesDir = new URL("languages/", srcDir);

const IMPORT_RE =
	/^import\s*\{([\s\S]*?)\}\s*from\s*['"]\.\/([\w.-]+)['"];?\s*$/gm;
const EXPORT_RE = /^export (function|async function|const|let)/gm;

async function buildLanguageRegistry() {
	const manifest = JSON.parse(
		await readFile(new URL("index.json", languagesDir), "utf8"),
	);
	const entries = await Promise.all(
		manifest.map(async (file) => {
			const language = JSON.parse(
				await readFile(new URL(file, languagesDir), "utf8"),
			);
			return [language.code, language];
		}),
	);
	return Object.fromEntries(entries);
}

async function bundleModules() {
	const files = (await readdir(srcDir)).filter(
		(file) => file.endsWith(".js") && file !== "sw.js",
	);
	const sources = new Map();
	for (const file of files)
		sources.set(file, await readFile(new URL(file, srcDir), "utf8"));

	const importedFilesOf = (source) =>
		[...source.matchAll(IMPORT_RE)].map((match) => match[2]);

	const order = [];
	const visiting = new Set();
	const visited = new Set();
	function visit(file) {
		if (visited.has(file)) return;
		if (visiting.has(file))
			throw new Error(`Circular import detected involving ${file}`);
		if (!sources.has(file)) throw new Error(`Unknown module import: ./${file}`);
		visiting.add(file);
		for (const dependency of importedFilesOf(sources.get(file)))
			visit(dependency);
		visiting.delete(file);
		visited.add(file);
		order.push(file);
	}
	for (const file of files) visit(file);

	return order
		.map((file) => {
			const body = sources
				.get(file)
				.replace(IMPORT_RE, "")
				.replace(EXPORT_RE, "$1")
				.trim();
			return `// ---- src/${file} ----\n${body}\n`;
		})
		.join("\n");
}

// The service worker's cache name is derived from a hash of everything it
// caches, instead of a hand-maintained version number. That way there is no
// "forgot to bump it" failure mode: any real change to the shipped app
// content produces a new cache automatically, and an unrelated change (docs,
// a comment) doesn't churn it for no reason.
//
// What gets hashed is read straight out of src/sw.js's own CORE_ASSETS list
// rather than a second, hand-kept list here — so if an asset (an icon, say)
// is ever added to what the service worker precaches, it's automatically
// covered by the hash too, with nothing else to remember to update.
async function buildServiceWorker(appJsContent) {
	const template = await readFile(new URL("sw.js", srcDir), "utf8");
	const coreAssetsMatch = template.match(/const CORE_ASSETS = \[([\s\S]*?)\];/);
	if (!coreAssetsMatch)
		throw new Error("Could not find CORE_ASSETS in src/sw.js");
	const paths = [...coreAssetsMatch[1].matchAll(/"([^"]+)"/g)].map(
		(match) => match[1],
	);

	const hash = createHash("sha256");
	for (const path of paths) {
		if (path === "./app.js") {
			hash.update(appJsContent);
			continue;
		}
		const file = path === "./" ? "index.html" : path.replace(/^\.\//, "");
		hash.update(await readFile(new URL(file, root)));
	}

	await writeFile(
		new URL("sw.js", root),
		template.replace("__CACHE_VERSION__", hash.digest("hex").slice(0, 10)),
	);
}

const languageRegistry = await buildLanguageRegistry();
const modules = await bundleModules();

const banner =
	"// Generated by `npm run build` from src/ — do not edit directly.\n\n";
const registry = `// ---- src/languages/*.json ----\nconst languageRegistry = ${JSON.stringify(languageRegistry)};\n\n`;
const appJs = banner + registry + modules;

await writeFile(new URL("app.js", root), appJs);
await buildServiceWorker(appJs);
